"""
rewards/gsm8k_reward.py

One job: given a generated response and a ground truth answer,
return 1.0 if correct, 0.0 if not.

This is the ONLY reward function in this project.
No learned reward model. No ambiguity. Binary and verifiable.

Why this matters for research validity:
If reward is ambiguous, differences in algorithm performance
could come from reward variance, not algorithm quality.
Binary verifiable reward eliminates this confound entirely.
"""

import re


def extract_answer(text: str) -> str | None:
    """
    Extract the numeric answer from a generated response.

    Looks for patterns in order of specificity:
    1. #### <number>  (GSM8K standard format)
    2. The answer is <number>
    3. = <number> at end of text
    4. Last standalone number in the text (fallback)

    Returns the extracted number as a string, or None if nothing found.
    """
    # Pattern 1: GSM8K standard #### format
    match = re.search(r"####\s*([\d,]+\.?\d*)", text)
    if match:
        return match.group(1).replace(",", "").strip()

    # Pattern 2: "the answer is X"
    match = re.search(r"[Tt]he answer is\s*([\d,]+\.?\d*)", text)
    if match:
        return match.group(1).replace(",", "").strip()

    # Pattern 3: "= X" near end of text
    match = re.search(r"=\s*([\d,]+\.?\d*)\s*$", text.strip())
    if match:
        return match.group(1).replace(",", "").strip()

    # Pattern 4: last standalone number (fallback — less reliable)
    numbers = re.findall(r"\b(\d+(?:,\d{3})*(?:\.\d+)?)\b", text)
    if numbers:
        return numbers[-1].replace(",", "").strip()

    return None


def compute_reward(generated_text: str, ground_truth_answer: str) -> float:
    """
    Compute binary reward for a generated response.

    Args:
        generated_text:      full text generated by the model
        ground_truth_answer: correct answer string from GSM8K (e.g. "42")

    Returns:
        1.0 if the extracted answer matches ground truth, else 0.0

    Note: comparison is done after stripping whitespace and
    normalizing decimal representation (42 == 42.0 == 42.00).
    """
    extracted = extract_answer(generated_text)

    if extracted is None:
        return 0.0

    # Normalize both to float for comparison
    # handles cases like "42" vs "42.0" vs "42.00"
    try:
        extracted_float = float(extracted)
        truth_float = float(ground_truth_answer.replace(",", "").strip())
        return 1.0 if abs(extracted_float - truth_float) < 1e-6 else 0.0
    except ValueError:
        # If either can't be converted to float, do string comparison
        return 1.0 if extracted.strip() == ground_truth_answer.strip() else 0.0


def compute_group_rewards(
    generated_texts: list[str],
    ground_truth_answer: str
) -> list[float]:
    """
    Compute rewards for a group of G rollouts for the same prompt.
    Used by the group-relative advantage estimator.

    Args:
        generated_texts:     list of G generated responses
        ground_truth_answer: single correct answer (same for all rollouts)

    Returns:
        list of G floats, each 0.0 or 1.0
    """
    return [compute_reward(text, ground_truth_answer) for text in generated_texts]
